### ISSUE TITLE
Album Art from local library doesn't show on Android

### ISSUE THREAD

**Issue by JHR46** [amp64/sonosbugtracker#28]
Album Art does not show up anywhere in the latest Android app.  V16.1 is fine.

**Comment by amp64** [comment]
Is this from one music service, all music services, local libraries?

**Comment by JHR46** [comment]
That's from the local library. Streamed material is fine. Very annoying as V16.1 is fine for all sources.  Note I have avoided updating firmware to latest. (can't give V# as am away on holidays)

**Comment by JHR46** [comment]
Sorry, marked as Completed in error.  Android S2 Build 80.10.06 rel 20241007.5d80fcb with firmware 81.1.58074 still does NOT show Album Art.

**Comment by amp64** [comment]
Finally fixed in 80.14.06
