### ISSUE TITLE
Favorites / Recently Added / View All - Does nothing

### ISSUE THREAD

**Issue by furacao14** [amp64/sonosbugtracker#37]
[https://en.community.sonos.com/controllers-and-music-services-229131/bug-report-favorites-recently-added-view-all-does-nothing-6920680](https://en.community.sonos.com/controllers-and-music-services-229131/bug-report-favorites-recently-added-view-all-does-nothing-6920680)

**Comment by amp64** [comment]
Confirmed this broke in Android 80.11.33

**Comment by furacao14** [comment]
Fixed on Android 80.14.06

**Comment by amp64** [comment]
Verified fixed.
